#version 430
layout(local_size_x=1, local_size_y=1, local_size_z=1) in;
layout(std430, binding=0) buffer ActiveTileCountBuffer {
    uint active_tile_count[];
};
layout(std430, binding=1) buffer ActiveTileDispatchArgsBuffer {
    uint active_tile_dispatch_args[];
};
void main() {
    active_tile_count[0] = 0u;
    active_tile_dispatch_args[0] = 0u;
    active_tile_dispatch_args[1] = 1u;
    active_tile_dispatch_args[2] = 1u;
}
