#version 430
layout(local_size_x={{LOCAL_SIZE}}, local_size_y=1, local_size_z=1) in;
uniform int cell_count;
layout(std430, binding=0) buffer PowderApplyIncoming {
    int apply_incoming[];
};
layout(std430, binding=1) buffer PowderApplyOutgoing {
    int apply_outgoing[];
};

void main() {
    int index = int(gl_GlobalInvocationID.x);
    if (index >= cell_count) {
        return;
    }
    apply_incoming[index] = -1;
    apply_outgoing[index] = -1;
}
