#version 430
layout(local_size_x={{LOCAL_SIZE}}, local_size_y={{LOCAL_SIZE}}, local_size_z=1) in;
uniform ivec2 grid_size;
layout(binding=0) uniform sampler2D source_tex;
layout(r32f, binding=1) writeonly uniform image2D dest_img;

void main() {
    ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
    if (gid.x >= grid_size.x || gid.y >= grid_size.y) {
        return;
    }
    imageStore(dest_img, gid, vec4(texelFetch(source_tex, gid, 0).x, 0.0, 0.0, 0.0));
}
