#version 430
layout(local_size_x=1, local_size_y=1, local_size_z=1) in;
uniform uint workgroups_per_tile;
layout(std430, binding=0) readonly buffer ActiveTileCountBuffer {
    uint active_tile_count[];
};
layout(std430, binding=1) buffer ActiveTileDispatchArgsBuffer {
    uint active_tile_dispatch_args[];
};

void main() {
    active_tile_dispatch_args[0] = active_tile_count[0] * max(workgroups_per_tile, 1u);
    active_tile_dispatch_args[1] = 1u;
    active_tile_dispatch_args[2] = 1u;
}
