
            #version 430
            layout(local_size_x={{LOCAL_SIZE}}, local_size_y=1, local_size_z=1) in;
            uniform int delta_count;
            layout(std430, binding=0) buffer GasDelta {
                int gas_delta[];
            };

            void main() {
                int index = int(gl_GlobalInvocationID.x);
                if (index >= delta_count) {
                    return;
                }
                gas_delta[index] = 0;
            }
            