
            #version 430
            layout(local_size_x=16, local_size_y=1, local_size_z=1) in;
            layout(std430, binding=0) buffer LightEmitterCount {
                uint light_emitter_count[];
            };

            void main() {
                uint index = gl_GlobalInvocationID.x;
                if (index < 16u) {
                    light_emitter_count[index] = 0u;
                }
            }
            