"""Mutate/table/entity/paging/control half of the http_api endpoints dict (lines 1391-1903)."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from oracle_game.world import WorldEngine


def _build_http_mutate_endpoints(engine: "WorldEngine", ctx) -> dict:
    """Build the http_mutate_endpoints half of the http_api endpoints dict."""

    target_query_fields = ctx.target_query_fields
    inline_target_query_optional_fields = ctx.inline_target_query_optional_fields
    observation_target_fields = ctx.observation_target_fields
    readback_plan_fields = ctx.readback_plan_fields
    observation_plan_fields = ctx.observation_plan_fields
    queued_mutation_result_fields = ctx.queued_mutation_result_fields

    return {
        "/api/readback/request": {
            "method": "POST",
            "body_fields": [
                "request_id",
                "center_x",
                "center_y",
                "width",
                "height",
                "channels",
                "observer_id",
                "label",
                *inline_target_query_optional_fields,
            ],
                "request_type": "readback_request",
                "response_fields": ["ok", "queued", "pending_commands", "request_id"],
                "response_type": "deferred_readback_request_result",
                "queueing": "deferred_command",
                "target_query_fields": target_query_fields,
                "supports_inline_target_queries": True,
            },
        "/api/readback/plan": {
            "method": "POST",
            "body_fields": [
                "request_id",
                "center_x",
                "center_y",
                "width",
                "height",
                "channels",
                "observer_id",
                "label",
                *inline_target_query_optional_fields,
            ],
            "request_type": "readback_request",
            "response_fields": ["ok", *readback_plan_fields],
            "response_type": "readback_plan_result",
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/readback/preview": {
            "method": "POST",
            "body_fields": [
                "request_id",
                "center_x",
                "center_y",
                "width",
                "height",
                "channels",
                "observer_id",
                "label",
                *inline_target_query_optional_fields,
            ],
            "request_type": "readback_request",
            "response_fields": ["ok", "request"],
            "response_type": "readback_preview_result",
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/frame/preview": {
            "method": "POST",
            "request_type": "frame_input",
            "response_fields": ["ok", "preview"],
            "response_type": "frame_preview_result",
        },
        "/api/frame/request": {
            "method": "POST",
            "request_type": "frame_input",
            "response_fields": ["ok", "queued", "pending_frames", "submission_id", "preview"],
            "response_type": "frame_submit_result",
            "queueing": "deferred_frame",
        },
        "/api/frame/submit": {
            "method": "POST",
            "request_type": "frame_input",
            "response_fields": ["ok", "queued", "pending_frames", "submission_id"],
            "response_type": "deferred_frame_submit_ack",
        },
        "/api/frame/cycle": {
            "method": "POST",
            "body_fields": ["apply_frame"],
            "request_type": "frame_input",
            "response_fields": ["ok", "applied", "queued", "pending_frames", "submission_id", "preview", "result"],
            "response_type": "frame_cycle_result",
            "queueing": "deferred_frame_when_applied",
        },
        "/api/frame/cancel": {
            "method": "POST",
            "body_fields": ["submission_id"],
            "response_fields": ["ok", "submission_id", "status", "pending_frames"],
            "request_type": "frame_cancel_request",
            "response_type": "frame_cancel_result",
        },
        "/api/frame/cancel_all": {
            "method": "POST",
            "response_fields": ["ok", "canceled_submission_ids", "pending_frames"],
            "response_type": "frame_cancel_all_result",
        },
        "/api/entity/states": {
            "method": "GET",
            "response_fields": ["entities"],
            "response_type": "entity_states_response",
        },
        "/api/entity/observations/state": {
            "method": "GET",
            "response_fields": ["observations", "targets", "requests"],
            "response_type": "entity_observation_runtime",
        },
        "/api/entity/observations/consumed": {
            "method": "GET",
            "response_fields": ["frame_id", "consumed", "consumed_readbacks", "observations", "entity_feedback"],
            "response_type": "entity_observation_consume_result",
        },
        "/api/entity/placeholders/state": {
            "method": "GET",
            "response_fields": ["placeholders"],
            "response_type": "entity_placeholders_response",
        },
        "/api/entity/feedback": {
            "method": "GET",
            "response_fields": ["feedback"],
            "response_type": "entity_feedback_response",
        },
        "/api/entity/controller/state": {
            "method": "GET",
            "response_fields": ["controller_state"],
            "response_type": "entity_controller_state",
        },
        "/api/entity/controller/state/set": {
            "method": "POST",
            "body_fields": ["controller_state"],
            "request_type": "entity_controller_state",
            "response_fields": ["ok", "queued", "pending_frames", "submission_id"],
            "response_type": "deferred_controller_state_result",
            "queueing": "deferred_frame",
        },
        "/api/entity/observations/set": {
            "method": "POST",
            "body_fields": ["observations"],
            "request_type": "entity_observation_spec[]",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "replace_semantics": "replace_all",
            "queueing": "deferred_command",
        },
        "/api/entity/observations/request": {
            "method": "POST",
            "body_fields": ["request_id", *observation_target_fields, "target_queries"],
            "request_type": "observation_target",
            "response_fields": ["ok", "queued", "pending_commands", "request_id"],
            "response_type": "deferred_observation_request_result",
            "queueing": "deferred_command",
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/entity/observations/preview": {
            "method": "POST",
            "body_fields": ["request_id", *observation_target_fields, "target_queries"],
            "request_type": "observation_target",
            "response_fields": ["ok", "request"],
            "response_type": "readback_preview_result",
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/entity/observations/plan": {
            "method": "POST",
            "body_fields": ["request_id", *observation_target_fields, "target_queries"],
            "request_type": "observation_target",
            "response_fields": ["ok", *observation_plan_fields],
            "response_type": "observation_plan_result",
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/entity/observations/consume": {
            "method": "POST",
            "response_fields": ["frame_id", "consumed", "consumed_readbacks", "observations", "entity_feedback"],
            "response_type": "entity_observation_consume_result",
        },
        "/api/entity/placeholders": {
            "method": "POST",
            "body_fields": ["placeholders"],
            "request_type": "entity_placeholder[]",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "replace_semantics": "replace_all",
            "queueing": "deferred_command",
        },
        "/api/entity/states/set": {
            "method": "POST",
            "body_fields": ["entities"],
            "request_type": "entity_state[]",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "replace_semantics": "replace_all",
            "queueing": "deferred_command",
        },
        "/api/entity/states/patch": {
            "method": "POST",
            "body_fields": ["patches"],
            "request_type": "entity_state_patch[]",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
        },
        "/api/entity/controller/turn": {
            "method": "POST",
            "body_fields": [
                "controller_state",
                "focus_center",
                "entities",
                "entity_placeholders",
                "patches",
                "observation_specs",
                "force_sources",
                "emitters",
                "target_queries",
                "change_intents",
                "carrier_intents",
                "observation_targets",
                "readback_requests",
                "commands",
            ],
            "request_type": "entity_controller_turn",
            "response_fields": ["ok", "queued", "pending_frames", "submission_id", "preview"],
            "response_type": "entity_controller_submit_result",
            "queueing": "deferred_frame",
        },
        "/api/entity/controller/preview": {
            "method": "POST",
            "body_fields": [
                "controller_state",
                "focus_center",
                "entities",
                "entity_placeholders",
                "patches",
                "observation_specs",
                "force_sources",
                "emitters",
                "target_queries",
                "change_intents",
                "carrier_intents",
                "observation_targets",
                "readback_requests",
                "commands",
            ],
            "request_type": "entity_controller_turn",
            "response_fields": ["ok", "preview"],
            "response_type": "entity_controller_preview_result",
        },
        "/api/entity/controller/submit": {
            "method": "POST",
            "body_fields": [
                "controller_state",
                "focus_center",
                "entities",
                "entity_placeholders",
                "patches",
                "observation_specs",
                "force_sources",
                "emitters",
                "target_queries",
                "change_intents",
                "carrier_intents",
                "observation_targets",
                "readback_requests",
                "commands",
            ],
            "request_type": "entity_controller_turn",
            "response_fields": ["ok", "queued", "pending_frames", "submission_id", "preview"],
            "response_type": "entity_controller_submit_result",
            "queueing": "deferred_frame",
        },
        "/api/entity/controller/cycle": {
            "method": "POST",
            "body_fields": [
                "apply_turn",
                "controller_state",
                "focus_center",
                "entities",
                "entity_placeholders",
                "patches",
                "observation_specs",
                "force_sources",
                "emitters",
                "target_queries",
                "change_intents",
                "carrier_intents",
                "observation_targets",
                "readback_requests",
                "commands",
            ],
            "request_type": "entity_controller_cycle",
            "response_fields": ["ok", "applied", "queued", "pending_frames", "submission_id", "preview", "result"],
            "response_type": "entity_controller_cycle_result",
            "queueing": "deferred_frame_when_applied",
        },
        "/api/paging/focus": {
            "method": "POST",
            "body_fields": ["x", "y", *inline_target_query_optional_fields],
            "response_fields": ["ok", "queued", "pending_commands", "target_center"],
            "request_type": "paging_focus_request",
            "response_type": "paging_focus_result",
            "queueing": "deferred_command",
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/paging/store/state": {
            "method": "GET",
            "response_fields": ["stored_stripes", "key_listing_supported", "stripe_keys"],
            "response_type": "page_store_state",
        },
        "/api/paging/store/has": {
            "method": "POST",
            "body_fields": ["update"],
            "request_type": "page_stripe_update",
            "response_fields": ["stored"],
            "response_type": "page_store_has_result",
        },
        "/api/paging/store/capture": {
            "method": "POST",
            "body_fields": ["update"],
            "request_type": "page_stripe_update",
            "response_fields": ["ok", "stored_stripes", "payload"],
            "response_type": "page_store_capture_result",
        },
        "/api/paging/store/load": {
            "method": "POST",
            "body_fields": ["update"],
            "request_type": "page_stripe_update",
            "response_fields": ["ok", "stored", "payload"],
            "response_type": "page_store_load_result",
        },
        "/api/paging/store/apply": {
            "method": "POST",
            "body_fields": ["update", "immediate"],
            "request_type": "page_stripe_update",
            "response_fields": ["ok", "stored", "queued", "pending_commands"],
            "response_type": "page_store_apply_result",
            "queueing": "deferred_command",
            "immediate_supported": True,
        },
        "/api/paging/store/save": {
            "method": "POST",
            "body_fields": ["update", "payload"],
            "request_type": "page_stripe_apply",
            "response_fields": ["ok", "stored_stripes"],
            "response_type": "page_store_save_result",
        },
        "/api/paging/store/export": {
            "method": "GET",
            "response_fields": ["stored_stripes", "key_listing_supported", "entries"],
            "response_type": "page_store_export",
        },
        "/api/paging/store/import": {
            "method": "POST",
            "body_fields": ["entries", "clear"],
            "request_type": "page_store_import",
            "response_fields": ["ok", "cleared", "imported", "stored_stripes"],
            "response_type": "page_store_import_result",
        },
        "/api/paging/store/clear": {
            "method": "POST",
            "response_fields": ["ok", "cleared", "stored_stripes"],
            "response_type": "page_store_clear_result",
        },
        "/api/paging/stripe/capture": {
            "method": "POST",
            "body_fields": ["update"],
            "request_type": "page_stripe_update",
            "response_fields": ["ok", "payload"],
            "response_type": "page_stripe_capture_result",
        },
        "/api/paging/stripe/apply": {
            "method": "POST",
            "body_fields": ["update", "payload", "immediate"],
            "request_type": "page_stripe_apply",
            "response_fields": ["ok", "queued", "pending_commands"],
            "response_type": "page_stripe_apply_result",
            "queueing": "deferred_command",
            "immediate_supported": True,
        },
        "/api/table/material": {
            "method": "POST",
            "body_fields": ["name", "fields"],
            "request_type": "material_patch",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
        },
        "/api/table/light": {
            "method": "POST",
            "body_fields": ["name", "fields"],
            "request_type": "light_patch",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
        },
        "/api/table/gas": {
            "method": "POST",
            "body_fields": ["name", "fields"],
            "request_type": "gas_patch",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
        },
        "/api/table/optic": {
            "method": "POST",
            "body_fields": ["material_name", "light_type", "fields"],
            "request_type": "optics_patch",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
        },
        "/api/table/reaction": {
            "method": "POST",
            "body_fields": ["index", "fields"],
            "request_type": "reaction_action_patch",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
        },
        "/api/table/reaction/delete": {
            "method": "POST",
            "body_fields": ["index"],
            "request_type": "reaction_action_delete_request",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
        },
        "/api/table/reaction_rule": {
            "method": "POST",
            "body_fields": ["rule_set", "index", "fields"],
            "request_type": "reaction_rule_patch",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
        },
        "/api/table/reaction_rule/delete": {
            "method": "POST",
            "body_fields": ["rule_set", "index"],
            "request_type": "reaction_rule_delete_request",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
        },
        "/api/table/materials/update": {
            "method": "POST",
            "body_fields": ["materials"],
            "request_type": "material[]",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "update_semantics": "merge_by_material_id",
            "queueing": "deferred_command",
        },
        "/api/table/gases/update": {
            "method": "POST",
            "body_fields": ["gases"],
            "request_type": "gas[]",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "update_semantics": "merge_by_species_id",
            "queueing": "deferred_command",
        },
        "/api/table/lights/update": {
            "method": "POST",
            "body_fields": ["lights"],
            "request_type": "light[]",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "update_semantics": "merge_by_light_type_id",
            "queueing": "deferred_command",
        },
        "/api/table/optics/update": {
            "method": "POST",
            "body_fields": ["optics"],
            "request_type": "optics[]",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "update_semantics": "merge_by_material_name_and_light_type",
            "queueing": "deferred_command",
        },
        "/api/table/reactions/update": {
            "method": "POST",
            "body_fields": ["actions", "rules"],
            "request_type": "reaction_table_append",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
        },
        "/api/table/reactions/replace": {
            "method": "POST",
            "body_fields": ["actions", "rules"],
            "request_type": "reaction_table_replace",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "replace_semantics": "replace_all",
            "queueing": "deferred_command",
        },
        "/api/control/pause": {"method": "POST", "response_fields": ["paused"], "response_type": "pause_result"},
        "/api/control/resume": {"method": "POST", "response_fields": ["paused"], "response_type": "resume_result"},
        "/api/control/step": {"method": "POST", "response_fields": ["single_step"], "response_type": "step_result"},
        "/api/control/speed": {
            "method": "POST",
            "body_fields": ["speed"],
            "response_fields": ["speed"],
            "request_type": "speed_request",
            "response_type": "speed_result",
        },
        "/api/control/reset": {
            "method": "POST",
            "response_fields": ["ok", "queued", "pending_commands"],
            "response_type": "control_reset_result",
            "queueing": "deferred_command",
        },
    }
