"""Read/control half of the http_api endpoints dict (lines 916-1390 of the original)."""

from __future__ import annotations

from typing import TYPE_CHECKING

from copy import deepcopy
from oracle_game.types import DebugView

if TYPE_CHECKING:
    from oracle_game.world import WorldEngine


def _build_http_read_endpoints(engine: "WorldEngine", ctx) -> dict:
    """Build the http_read_endpoints half of the http_api endpoints dict."""

    force_source_fields = ctx.force_source_fields
    emitter_fields = ctx.emitter_fields
    target_query_fields = ctx.target_query_fields
    inline_target_query_optional_fields = ctx.inline_target_query_optional_fields
    queued_mutation_result_fields = ctx.queued_mutation_result_fields
    debug_view_parameterized_views = ctx.debug_view_parameterized_views
    gas_read_options = ctx.gas_read_options
    optics_read_options = ctx.optics_read_options

    return {
        "/api/meta/capabilities": {
            "method": "GET",
            "response_type": "engine_capabilities",
        },
        "/api/read/cells": {
            "method": "GET",
            "query_fields": ["x", "y", "w", "h"],
            "response_type": "cell_window",
            "query_coord_space": "world",
            "default_origin": [0, 0],
            "default_size": [16, 16],
        },
        "/api/read/temperature": {
            "method": "GET",
            "query_fields": ["x", "y", "w", "h"],
            "response_type": "temperature_window",
            "query_coord_space": "world",
            "default_origin": [0, 0],
            "omitted_size_means": "full_buffer",
        },
        "/api/read/gas": {
            "method": "GET",
            "query_fields": ["species"],
            "response_type": "gas_window",
            "coord_space": "gas",
            "coverage": "full_buffer",
            **deepcopy(gas_read_options),
        },
        "/api/read/pressure": {
            "method": "GET",
            "response_type": "pressure_window",
            "coord_space": "gas",
            "coverage": "full_buffer",
        },
        "/api/read/gas_runtime": {
            "method": "GET",
            "response_type": "gas_runtime",
            "snapshot_scope": "current_world_state",
            "snapshot_kind": "latest_solver_runtime",
        },
        "/api/read/heat_runtime": {
            "method": "GET",
            "response_type": "heat_runtime",
            "snapshot_scope": "current_world_state",
            "snapshot_kind": "latest_solver_runtime",
        },
        "/api/read/liquid_runtime": {
            "method": "GET",
            "response_type": "liquid_runtime",
            "snapshot_scope": "current_world_state",
            "snapshot_kind": "latest_solver_runtime",
        },
        "/api/read/reaction_runtime": {
            "method": "GET",
            "response_type": "reaction_runtime",
            "snapshot_scope": "current_world_state",
            "snapshot_kind": "latest_solver_runtime",
        },
        "/api/read/collapse_runtime": {
            "method": "GET",
            "response_type": "collapse_runtime",
            "snapshot_scope": "current_world_state",
            "snapshot_kind": "latest_solver_runtime",
        },
        "/api/read/optics_runtime": {
            "method": "GET",
            "response_type": "optics_runtime",
            "snapshot_scope": "current_world_state",
            "snapshot_kind": "latest_solver_runtime",
        },
        "/api/read/light": {
            "method": "GET",
            "response_type": "visible_illumination",
            "light_type": "visible_light",
            "coord_space": "world",
            "coverage": "full_buffer",
        },
        "/api/read/debug_frame": {
            "method": "GET",
            "query_fields": ["view", "gas_species", "light"],
            "response_type": "debug_frame",
            "default_view": engine.default_debug_view.value,
            "allowed_views": [view.value for view in DebugView],
            "parameterized_views": deepcopy(debug_view_parameterized_views),
        },
        "/api/read/optics": {
            "method": "GET",
            "query_fields": ["x", "y", "w", "h", "light"],
            "response_type": "optics_window",
            "query_coord_space": "world",
            "default_origin": [0, 0],
            "omitted_size_means": "full_buffer",
            **deepcopy(optics_read_options),
        },
        "/api/read/velocity": {
            "method": "GET",
            "response_type": "velocity_window",
            "coord_space": "gas",
            "coverage": "full_buffer",
        },
        "/api/read/forces": {
            "method": "GET",
            "response_type": "force_sources_response",
            "snapshot_scope": "current_world_state",
            "snapshot_kind": "current_persistent_state",
        },
        "/api/read/emitters": {
            "method": "GET",
            "response_type": "emitters",
            "snapshot_scope": "current_world_state",
            "snapshot_kind": "current_persistent_state",
        },
        "/api/read/active": {
            "method": "GET",
            "response_type": "active_runtime",
            "snapshot_scope": "current_world_state",
            "snapshot_kind": "current_runtime_state",
        },
        "/api/read/motion": {
            "method": "GET",
            "response_type": "motion_runtime",
            "snapshot_scope": "current_world_state",
            "snapshot_kind": "latest_solver_runtime",
        },
        "/api/read/bridge_runtime": {
            "method": "GET",
            "response_type": "bridge_runtime",
            "snapshot_scope": "current_bridge_state",
            "snapshot_kind": "current_runtime_state",
        },
        "/api/read/bridge_resources": {
            "method": "GET",
            "response_type": "bridge_resource_catalog",
            "snapshot_scope": "current_bridge_state",
            "snapshot_kind": "current_resource_catalog",
        },
        "/api/read/bridge_typed_table": {
            "method": "GET",
            "query_fields": ["name"],
            "response_type": "bridge_typed_table_snapshot",
            "snapshot_scope": "current_bridge_state",
            "snapshot_kind": "current_typed_table_snapshot",
        },
        "/api/read/bridge_typed_table_slice": {
            "method": "GET",
            "query_fields": ["name", "offset", "limit"],
            "response_type": "bridge_typed_table_slice_snapshot",
            "snapshot_scope": "current_bridge_state",
            "snapshot_kind": "current_typed_table_snapshot",
            "default_offset": 0,
            "default_limit": 64,
        },
        "/api/read/bridge_shadow_buffer": {
            "method": "GET",
            "query_fields": ["name"],
            "response_type": "bridge_shadow_buffer_snapshot",
            "snapshot_scope": "current_bridge_state",
            "snapshot_kind": "current_shadow_buffer_snapshot",
        },
        "/api/read/bridge_shadow_buffer_slice": {
            "method": "GET",
            "query_fields": ["name", "offset", "limit"],
            "response_type": "bridge_shadow_buffer_slice_snapshot",
            "snapshot_scope": "current_bridge_state",
            "snapshot_kind": "current_shadow_buffer_snapshot",
            "default_offset": 0,
            "default_limit": 64,
        },
        "/api/read/bridge_shadow_buffer_window": {
            "method": "GET",
            "query_fields": ["name", "x", "y", "w", "h"],
            "response_type": "bridge_shadow_buffer_window_snapshot",
            "snapshot_scope": "current_bridge_state",
            "snapshot_kind": "current_shadow_buffer_snapshot",
            "query_coord_space": "buffer",
            "default_origin": [0, 0],
            "default_size": [16, 16],
        },
        "/api/read/bridge_shadow_buffer_world_window": {
            "method": "GET",
            "query_fields": ["name", "x", "y", "w", "h"],
            "response_type": "bridge_shadow_buffer_world_window_snapshot",
            "snapshot_scope": "current_bridge_state",
            "snapshot_kind": "current_shadow_buffer_snapshot",
            "query_coord_space": "world",
            "default_origin": [0, 0],
            "default_size": [16, 16],
        },
        "/api/read/bridge_shadow_buffer_gas_window": {
            "method": "GET",
            "query_fields": ["name", "x", "y", "w", "h"],
            "response_type": "bridge_shadow_buffer_gas_window_snapshot",
            "snapshot_scope": "current_bridge_state",
            "snapshot_kind": "current_shadow_buffer_snapshot",
            "query_coord_space": "gas",
            "default_origin": [0, 0],
            "default_size": [4, 4],
        },
        "/api/read/bridge_uploads": {
            "method": "GET",
            "response_type": "bridge_upload_snapshot",
            "snapshot_scope": "current_bridge_state",
            "snapshot_kind": "latest_upload_snapshot",
        },
        "/api/read/bridge_frame": {
            "method": "GET",
            "response_type": "bridge_frame_snapshot",
            "snapshot_scope": "current_bridge_state",
            "snapshot_kind": "latest_frame_snapshot",
        },
        "/api/read/paging": {
            "method": "GET",
            "response_type": "paging_state",
            "snapshot_scope": "current_world_state",
            "snapshot_kind": "current_paging_state",
        },
        "/api/control/state": {
            "method": "GET",
            "response_fields": ["paused", "speed", "single_step"],
            "response_type": "control_state",
        },
        "/api/commands/pending": {
            "method": "GET",
            "response_fields": ["pending", "commands"],
            "response_type": "pending_commands",
        },
        "/api/targets/preview": {
            "method": "POST",
            "body_fields": ["target_queries"],
            "request_type": "target_query[]",
            "response_fields": ["ok", "resolved_targets"],
            "response_type": "target_preview_result",
        },
        "/api/commands/preview": {
            "method": "POST",
            "body_fields": ["command", "target_queries"],
            "request_type": "world_command",
            "response_fields": ["ok", "command"],
            "response_type": "command_preview_result",
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/commands/request": {
            "method": "POST",
            "body_fields": ["command", "target_queries"],
            "request_type": "world_command",
            "response_fields": ["ok", "queued", "pending_commands", "command"],
            "response_type": "command_request_result",
            "queueing": "deferred_command",
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/change_intents/preview": {
            "method": "POST",
            "body_fields": ["intent", "target_queries"],
            "request_type": "change_intent",
            "response_fields": ["ok", "resolved_intent"],
            "response_type": "change_intent_preview_result",
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/change_intents/request": {
            "method": "POST",
            "body_fields": ["intent", "target_queries"],
            "request_type": "change_intent",
            "response_fields": ["ok", "queued", "pending_commands", "resolved_intent"],
            "response_type": "change_intent_request_result",
            "queueing": "deferred_command",
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/carrier_intents/preview": {
            "method": "POST",
            "body_fields": ["intent", "target_queries"],
            "request_type": "carrier_intent",
            "response_fields": ["ok", "resolved_intent"],
            "response_type": "carrier_intent_preview_result",
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/carrier_intents/request": {
            "method": "POST",
            "body_fields": ["intent", "target_queries"],
            "request_type": "carrier_intent",
            "response_fields": ["ok", "queued", "pending_commands", "resolved_intent"],
            "response_type": "carrier_intent_request_result",
            "queueing": "deferred_command",
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/readback/pending": {
            "method": "GET",
            "response_fields": [
                "queued",
                "queued_commands",
                "pending",
                "pending_requests",
                "inflight",
                "inflight_requests",
                "ready",
            ],
            "response_type": "readback_state",
        },
        "/api/readback/ready": {
            "method": "GET",
            "response_fields": ["ready", "results"],
            "response_type": "readback_ready",
        },
        "/api/readback/poll": {
            "method": "GET",
            "query_fields": ["request_id"],
            "response_fields": ["ready", "status", "result"],
            "response_type": "readback_poll",
        },
        "/api/readback/poll_all": {
            "method": "GET",
            "response_fields": ["results"],
            "response_type": "readback_poll_all",
        },
        "/api/readback/status": {
            "method": "GET",
            "query_fields": ["request_id"],
            "response_fields": ["request_id", "status"],
            "response_type": "readback_status",
        },
        "/api/readback/cancel": {
            "method": "POST",
            "body_fields": ["request_id"],
            "response_fields": ["ok", "request_id", "status"],
            "request_type": "readback_cancel_request",
            "response_type": "readback_cancel_result",
        },
        "/api/frame/pending": {
            "method": "GET",
            "response_fields": ["pending", "submission_ids"],
            "response_type": "frame_pending_state",
        },
        "/api/frame/pending/detail": {
            "method": "GET",
            "response_fields": ["pending", "frames"],
            "response_type": "pending_frame_details",
        },
        "/api/frame/state": {
            "method": "GET",
            "response_fields": [
                "pending",
                "pending_submission_ids",
                "ready",
                "ready_submission_ids",
                "canceled_submission_ids",
            ],
            "response_type": "frame_state",
        },
        "/api/frame/output/poll": {
            "method": "GET",
            "query_fields": ["submission_id"],
            "response_fields": ["ready", "status", "output"],
            "response_type": "frame_output_poll",
        },
        "/api/frame/output/ready": {
            "method": "GET",
            "response_fields": ["ready", "outputs"],
            "response_type": "frame_output_ready",
        },
        "/api/frame/output/poll_all": {
            "method": "GET",
            "response_fields": ["outputs"],
            "response_type": "frame_output_poll_all",
        },
        "/api/frame/output/status": {
            "method": "GET",
            "query_fields": ["submission_id"],
            "response_fields": ["submission_id", "status"],
            "response_type": "frame_submission_status",
        },
        "/api/table/materials": {"method": "GET", "response_type": "materials_table"},
        "/api/table/gases": {"method": "GET", "response_type": "gases_table"},
        "/api/table/lights": {"method": "GET", "response_type": "lights_table"},
        "/api/table/optics": {"method": "GET", "response_type": "optics_table"},
        "/api/table/reactions": {"method": "GET", "response_type": "reactions_table"},
        "/api/material/write": {
            "method": "POST",
            "body_fields": ["x", "y", "material", "radius", "immediate", *inline_target_query_optional_fields],
            "request_type": "material_injector",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
            "immediate_supported": True,
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/material/fill": {
            "method": "POST",
            "body_fields": ["x", "y", "width", "height", "material", "immediate", *inline_target_query_optional_fields],
            "request_type": "material_fill_request",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
            "immediate_supported": True,
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/inject/temperature": {
            "method": "POST",
            "body_fields": ["x", "y", "delta", "radius", "immediate", *inline_target_query_optional_fields],
            "request_type": "temperature_injector",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
            "immediate_supported": True,
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/inject/velocity": {
            "method": "POST",
            "body_fields": ["x", "y", "velocity", "radius", "carrier", "mode", "immediate", *inline_target_query_optional_fields],
            "request_type": "velocity_injector",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
            "immediate_supported": True,
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/inject/gas": {
            "method": "POST",
            "body_fields": ["x", "y", "species", "amount", "radius", "immediate", *inline_target_query_optional_fields],
            "request_type": "gas_injector",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
            "immediate_supported": True,
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/inject/force": {
            "method": "POST",
            "body_fields": [*force_source_fields, "immediate", *inline_target_query_optional_fields],
            "request_type": "force_injector",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
            "immediate_supported": True,
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
        "/api/force_sources/set": {
            "method": "POST",
            "body_fields": ["force_sources"],
            "request_type": "force_source[]",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "replace_semantics": "replace_all",
            "queueing": "deferred_command",
        },
        "/api/emitters/set": {
            "method": "POST",
            "body_fields": ["emitters"],
            "request_type": "emitter[]",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "replace_semantics": "replace_all",
            "queueing": "deferred_command",
        },
        "/api/inject/light": {
            "method": "POST",
            "body_fields": [*emitter_fields, "immediate", *inline_target_query_optional_fields],
            "request_type": "light_injector",
            "response_fields": queued_mutation_result_fields,
            "response_type": "queued_mutation_result",
            "queueing": "deferred_command",
            "immediate_supported": True,
            "target_query_fields": target_query_fields,
            "supports_inline_target_queries": True,
        },
    }
