"""Frame input, pending-frame-detail, preview and output keys."""

from __future__ import annotations

from typing import Any, TYPE_CHECKING

from oracle_game.readback_contract import READBACK_ALLOWED_CHANNELS
from oracle_game.world_constants import (
    CARDINAL_DIRECTION_VECTORS,
    IGNORED_ANCHOR_FILTERS,
    MAX_ASYNC_READBACK_HEIGHT,
    MAX_ASYNC_READBACK_WIDTH,
    TARGET_QUERY_DISTANCE_HINT_CELLS,
    TERRAIN_ANCHOR_FILTERS,
)


if TYPE_CHECKING:
    from oracle_game.world import WorldEngine


def _capabilities_frame_section(engine: "WorldEngine", ctx) -> dict[str, Any]:
    """Build the frame portion of the engine capabilities schema."""

    force_source_fields = ctx.force_source_fields
    emitter_fields = ctx.emitter_fields
    entity_state_fields = ctx.entity_state_fields
    entity_placeholder_fields = ctx.entity_placeholder_fields
    target_query_fields = ctx.target_query_fields
    target_query_overlay_fields = ctx.target_query_overlay_fields
    readback_request_fields = ctx.readback_request_fields
    observation_target_fields = ctx.observation_target_fields
    change_intent_fields = ctx.change_intent_fields
    carrier_intent_fields = ctx.carrier_intent_fields
    world_command_material_alias_fields_by_kind = ctx.world_command_material_alias_fields_by_kind
    world_command_collection_item_types_by_kind = ctx.world_command_collection_item_types_by_kind
    public_world_command_kinds = ctx.public_world_command_kinds
    frame_input_field_order = ctx.frame_input_field_order
    pending_frame_detail_field_order = ctx.pending_frame_detail_field_order
    frame_preview_field_order = ctx.frame_preview_field_order
    frame_output_field_order = ctx.frame_output_field_order

    return {
        "frame_input": {
            "field_order": frame_input_field_order,
            "fields": {
                "submission_id": {"type": "int", "optional": True},
                "focus_center": {"type": "cell_xy", "optional": True},
                "controller_state": {"type": "json", "optional": True},
                "controller_state_provided": {"type": "bool", "optional": True},
                "entities": {"type": "entity_state[]", "optional": True, "replace_semantics": "replace_all"},
                "entity_placeholders": {
                    "type": "entity_placeholder[]",
                    "optional": True,
                    "replace_semantics": "replace_all",
                },
                "force_sources": {
                    "type": "force_source[]",
                    "optional": True,
                    "fields": force_source_fields,
                    "replace_semantics": "replace_all",
                },
                "emitters": {
                    "type": "emitter[]",
                    "optional": True,
                    "fields": emitter_fields,
                    "replace_semantics": "replace_all",
                },
                "target_queries": {"type": "target_query[]", "optional": True},
                "change_intents": {"type": "change_intent[]", "optional": True},
                "carrier_intents": {"type": "carrier_intent[]", "optional": True},
                "observation_targets": {"type": "observation_target[]", "optional": True},
                "readback_requests": {"type": "readback_request[]", "optional": True},
                "commands": {"type": "world_command[]", "optional": True},
            },
            "nested_types": {
                "entity_state": {
                    "fields": entity_state_fields,
                    "material_alias_fields": ["placeholder_material"],
                    "field_types": {
                        "entity_id": {"type": "int"},
                        "x": {"type": "int"},
                        "y": {"type": "int"},
                        "width": {"type": "int"},
                        "height": {"type": "int"},
                        "velocity_xy": {"type": "float2"},
                        "facing_xy": {"type": "float2", "optional": True},
                        "placeholder_material": {"type": "str"},
                        "tags": {"type": "str[]"},
                        "observe_channels": {"type": "str[]"},
                        "observe_pad_cells": {"type": "int"},
                        "observe_width": {"type": "int", "optional": True},
                        "observe_height": {"type": "int", "optional": True},
                        "observe_label": {"type": "str", "optional": True},
                    },
                },
                "entity_placeholder": {
                    "fields": entity_placeholder_fields,
                    "material_alias_fields": ["material"],
                    "field_types": {
                        "entity_id": {"type": "int"},
                        "x": {"type": "int"},
                        "y": {"type": "int"},
                        "width": {"type": "int"},
                        "height": {"type": "int"},
                        "material": {"type": "str"},
                    },
                },
                "force_source": {
                    "fields": force_source_fields,
                    "field_types": {
                        "x": {"type": "float"},
                        "y": {"type": "float"},
                        "direction": {"type": "float2"},
                        "radius": {"type": "float"},
                        "strength": {"type": "float"},
                        "lifetime": {"type": "float"},
                    },
                },
                "emitter": {
                    "fields": emitter_fields,
                    "field_types": {
                        "x": {"type": "int"},
                        "y": {"type": "int"},
                        "light_type": {"type": "str"},
                        "strength": {"type": "float"},
                        "radius": {"type": "int"},
                        "direction": {"type": "float2"},
                        "spread": {"type": "float"},
                    },
                },
                "target_query": {
                    "fields": target_query_fields,
                    "directions": [*CARDINAL_DIRECTION_VECTORS.keys(), "forward", "backward"],
                    "distance_hints": sorted(TARGET_QUERY_DISTANCE_HINT_CELLS),
                    "terrain_anchor_filters": sorted(TERRAIN_ANCHOR_FILTERS),
                    "ignored_anchor_filters": sorted(IGNORED_ANCHOR_FILTERS),
                    "field_types": {
                        "query_id": {"type": "str"},
                        "anchor_filters": {"type": "str[]"},
                        "source_entity_id": {"type": "int", "optional": True},
                        "source_x": {"type": "int", "optional": True},
                        "source_y": {"type": "int", "optional": True},
                        "anchor_entity_id": {"type": "int", "optional": True},
                        "direction": {"type": "str", "optional": True},
                        "distance_cells": {"type": "int"},
                        "distance_meters": {"type": "float", "optional": True},
                        "distance_hint": {"type": "str", "optional": True},
                        "require_empty": {"type": "bool"},
                        "search_radius": {"type": "int"},
                        "label": {"type": "str", "optional": True},
                    },
                },
                "change_intent": {
                    "fields": change_intent_fields,
                    "velocity_carriers": ["cell", "flow", "both"],
                    "velocity_modes": ["add", "set"],
                    "fallback_modes": ["nearest_empty", "source"],
                    "material_alias_fields": ["material"],
                    "field_types": {
                        "intent_id": {"type": "str"},
                        "target_query_id": {"type": "str", "optional": True},
                        "center_x": {"type": "int", "optional": True},
                        "center_y": {"type": "int", "optional": True},
                        "target_dx": {"type": "int"},
                        "target_dy": {"type": "int"},
                        "radius": {"type": "int"},
                        "material": {"type": "str", "optional": True},
                        "temperature_delta": {"type": "float"},
                        "velocity": {"type": "float2", "optional": True},
                        "velocity_carrier": {"type": "str"},
                        "velocity_mode": {"type": "str"},
                        "require_empty": {"type": "bool"},
                        "fallback_mode": {"type": "str"},
                        "fallback_radius": {"type": "int"},
                        "potency": {"type": "float"},
                        "stability": {"type": "float"},
                        "label": {"type": "str", "optional": True},
                    },
                },
                "carrier_intent": {
                    "fields": carrier_intent_fields,
                    "kinds": ["material", "gas", "light", "force"],
                    "release_modes": ["impact", "beam", "projectile"],
                    "fallback_modes": ["nearest_empty", "source"],
                    "material_alias_fields": ["material"],
                    "field_types": {
                        "intent_id": {"type": "str"},
                        "kind": {"type": "str"},
                        "target_query_id": {"type": "str", "optional": True},
                        "center_x": {"type": "int", "optional": True},
                        "center_y": {"type": "int", "optional": True},
                        "source_entity_id": {"type": "int", "optional": True},
                        "source_x": {"type": "int", "optional": True},
                        "source_y": {"type": "int", "optional": True},
                        "target_dx": {"type": "int"},
                        "target_dy": {"type": "int"},
                        "radius": {"type": "int"},
                        "material": {"type": "str", "optional": True},
                        "gas_species": {"type": "str", "optional": True},
                        "gas_amount": {"type": "float"},
                        "light_type": {"type": "str", "optional": True},
                        "light_strength": {"type": "float"},
                        "light_spread": {"type": "float"},
                        "force_radius": {"type": "float"},
                        "force_strength": {"type": "float"},
                        "force_lifetime": {"type": "float"},
                        "release_mode": {"type": "str"},
                        "require_empty": {"type": "bool"},
                        "fallback_mode": {"type": "str"},
                        "fallback_radius": {"type": "int"},
                        "potency": {"type": "float"},
                        "stability": {"type": "float"},
                        "label": {"type": "str", "optional": True},
                    },
                },
                "observation_target": {
                    "fields": observation_target_fields,
                    "allowed_channels": list(READBACK_ALLOWED_CHANNELS),
                    "field_types": {
                        "observer_id": {"type": "int"},
                        "channels": {"type": "str[]"},
                        "center_x": {"type": "int", "optional": True},
                        "center_y": {"type": "int", "optional": True},
                        "width": {"type": "int", "optional": True},
                        "height": {"type": "int", "optional": True},
                        "entity_id": {"type": "int", "optional": True},
                        "pad_cells": {"type": "int"},
                        "label": {"type": "str", "optional": True},
                        "target_query_id": {"type": "str", "optional": True},
                        "target_dx": {"type": "int"},
                        "target_dy": {"type": "int"},
                    },
                },
                "readback_request": {
                    "fields": readback_request_fields,
                    "allowed_channels": list(READBACK_ALLOWED_CHANNELS),
                    "max_async_window_size": [int(MAX_ASYNC_READBACK_WIDTH), int(MAX_ASYNC_READBACK_HEIGHT)],
                    "field_types": {
                        "request_id": {"type": "int", "optional": True},
                        "center_x": {"type": "int", "optional": True},
                        "center_y": {"type": "int", "optional": True},
                        "width": {"type": "int"},
                        "height": {"type": "int"},
                        "channels": {"type": "str[]"},
                        "observer_id": {"type": "int", "optional": True},
                        "label": {"type": "str", "optional": True},
                        "target_query_id": {"type": "str", "optional": True},
                        "target_dx": {"type": "int"},
                        "target_dy": {"type": "int"},
                    },
                },
                "world_command": {
                    "fields": ["kind", "payload"],
                    "public_kinds": public_world_command_kinds,
                    "target_query_overlay_fields": ["target_query_id", "target_dx", "target_dy"],
                    "material_alias_fields_by_kind": world_command_material_alias_fields_by_kind,
                    "collection_item_types_by_kind": world_command_collection_item_types_by_kind,
                    "field_types": {
                        "kind": {"type": "str"},
                        "payload": {"type": "json"},
                    },
                },
            },
        },
        "pending_frame_detail": {
            "field_order": pending_frame_detail_field_order,
            "fields": {
                "submission_id": {"type": "int", "optional": True},
                "focus_center": {"type": "cell_xy", "optional": True},
                "controller_state": {"type": "json", "optional": True},
                "controller_state_provided": {"type": "bool", "optional": True},
                "entities": {"type": "entity_state[]", "optional": True, "replace_semantics": "replace_all"},
                "entity_placeholders": {
                    "type": "entity_placeholder[]",
                    "optional": True,
                    "replace_semantics": "replace_all",
                },
                "force_sources": {
                    "type": "force_source[]",
                    "optional": True,
                    "fields": force_source_fields,
                    "replace_semantics": "replace_all",
                },
                "emitters": {
                    "type": "emitter[]",
                    "optional": True,
                    "fields": emitter_fields,
                    "replace_semantics": "replace_all",
                },
                "target_queries": {"type": "target_query[]", "optional": True},
                "change_intents": {"type": "change_intent[]", "optional": True},
                "carrier_intents": {"type": "carrier_intent[]", "optional": True},
                "observation_targets": {"type": "observation_target[]", "optional": True},
                "readback_requests": {"type": "readback_request[]", "optional": True},
                "commands": {"type": "world_command[]", "optional": True},
                "preview": {"type": "frame_preview"},
            },
            "nested_types": {
                "entity_state": {
                    "fields": entity_state_fields,
                    "material_alias_fields": ["placeholder_material"],
                    "field_types": {
                        "entity_id": {"type": "int"},
                        "x": {"type": "int"},
                        "y": {"type": "int"},
                        "width": {"type": "int"},
                        "height": {"type": "int"},
                        "velocity_xy": {"type": "float2"},
                        "facing_xy": {"type": "float2", "optional": True},
                        "placeholder_material": {"type": "str"},
                        "tags": {"type": "str[]"},
                        "observe_channels": {"type": "str[]"},
                        "observe_pad_cells": {"type": "int"},
                        "observe_width": {"type": "int", "optional": True},
                        "observe_height": {"type": "int", "optional": True},
                        "observe_label": {"type": "str", "optional": True},
                    },
                },
                "entity_placeholder": {
                    "fields": entity_placeholder_fields,
                    "material_alias_fields": ["material"],
                    "field_types": {
                        "entity_id": {"type": "int"},
                        "x": {"type": "int"},
                        "y": {"type": "int"},
                        "width": {"type": "int"},
                        "height": {"type": "int"},
                        "material": {"type": "str"},
                    },
                },
                "force_source": {
                    "fields": force_source_fields,
                    "field_types": {
                        "x": {"type": "float"},
                        "y": {"type": "float"},
                        "direction": {"type": "float2"},
                        "radius": {"type": "float"},
                        "strength": {"type": "float"},
                        "lifetime": {"type": "float"},
                    },
                },
                "emitter": {
                    "fields": emitter_fields,
                    "field_types": {
                        "x": {"type": "int"},
                        "y": {"type": "int"},
                        "light_type": {"type": "str"},
                        "strength": {"type": "float"},
                        "radius": {"type": "int"},
                        "direction": {"type": "float2"},
                        "spread": {"type": "float"},
                    },
                },
                "target_query": {
                    "fields": target_query_fields,
                    "directions": [*CARDINAL_DIRECTION_VECTORS.keys(), "forward", "backward"],
                    "distance_hints": sorted(TARGET_QUERY_DISTANCE_HINT_CELLS),
                    "terrain_anchor_filters": sorted(TERRAIN_ANCHOR_FILTERS),
                    "ignored_anchor_filters": sorted(IGNORED_ANCHOR_FILTERS),
                    "field_types": {
                        "query_id": {"type": "str"},
                        "anchor_filters": {"type": "str[]"},
                        "source_entity_id": {"type": "int", "optional": True},
                        "source_x": {"type": "int", "optional": True},
                        "source_y": {"type": "int", "optional": True},
                        "anchor_entity_id": {"type": "int", "optional": True},
                        "direction": {"type": "str", "optional": True},
                        "distance_cells": {"type": "int"},
                        "distance_meters": {"type": "float", "optional": True},
                        "distance_hint": {"type": "str", "optional": True},
                        "require_empty": {"type": "bool"},
                        "search_radius": {"type": "int"},
                        "label": {"type": "str", "optional": True},
                    },
                },
                "change_intent": {
                    "fields": change_intent_fields,
                    "velocity_carriers": ["cell", "flow", "both"],
                    "velocity_modes": ["add", "set"],
                    "fallback_modes": ["nearest_empty", "source"],
                    "material_alias_fields": ["material"],
                    "field_types": {
                        "intent_id": {"type": "str"},
                        "target_query_id": {"type": "str", "optional": True},
                        "center_x": {"type": "int", "optional": True},
                        "center_y": {"type": "int", "optional": True},
                        "target_dx": {"type": "int"},
                        "target_dy": {"type": "int"},
                        "radius": {"type": "int"},
                        "material": {"type": "str", "optional": True},
                        "temperature_delta": {"type": "float"},
                        "velocity": {"type": "float2", "optional": True},
                        "velocity_carrier": {"type": "str"},
                        "velocity_mode": {"type": "str"},
                        "require_empty": {"type": "bool"},
                        "fallback_mode": {"type": "str"},
                        "fallback_radius": {"type": "int"},
                        "potency": {"type": "float"},
                        "stability": {"type": "float"},
                        "label": {"type": "str", "optional": True},
                    },
                },
                "carrier_intent": {
                    "fields": carrier_intent_fields,
                    "kinds": ["material", "gas", "light", "force"],
                    "release_modes": ["impact", "beam", "projectile"],
                    "fallback_modes": ["nearest_empty", "source"],
                    "material_alias_fields": ["material"],
                    "field_types": {
                        "intent_id": {"type": "str"},
                        "kind": {"type": "str"},
                        "target_query_id": {"type": "str", "optional": True},
                        "center_x": {"type": "int", "optional": True},
                        "center_y": {"type": "int", "optional": True},
                        "source_entity_id": {"type": "int", "optional": True},
                        "source_x": {"type": "int", "optional": True},
                        "source_y": {"type": "int", "optional": True},
                        "target_dx": {"type": "int"},
                        "target_dy": {"type": "int"},
                        "radius": {"type": "int"},
                        "material": {"type": "str", "optional": True},
                        "gas_species": {"type": "str", "optional": True},
                        "gas_amount": {"type": "float"},
                        "light_type": {"type": "str", "optional": True},
                        "light_strength": {"type": "float"},
                        "light_spread": {"type": "float"},
                        "force_radius": {"type": "float"},
                        "force_strength": {"type": "float"},
                        "force_lifetime": {"type": "float"},
                        "release_mode": {"type": "str"},
                        "require_empty": {"type": "bool"},
                        "fallback_mode": {"type": "str"},
                        "fallback_radius": {"type": "int"},
                        "potency": {"type": "float"},
                        "stability": {"type": "float"},
                        "label": {"type": "str", "optional": True},
                    },
                },
                "observation_target": {
                    "fields": observation_target_fields,
                    "allowed_channels": list(READBACK_ALLOWED_CHANNELS),
                    "field_types": {
                        "observer_id": {"type": "int"},
                        "channels": {"type": "str[]"},
                        "center_x": {"type": "int", "optional": True},
                        "center_y": {"type": "int", "optional": True},
                        "width": {"type": "int", "optional": True},
                        "height": {"type": "int", "optional": True},
                        "entity_id": {"type": "int", "optional": True},
                        "pad_cells": {"type": "int"},
                        "label": {"type": "str", "optional": True},
                        "target_query_id": {"type": "str", "optional": True},
                        "target_dx": {"type": "int"},
                        "target_dy": {"type": "int"},
                    },
                },
                "readback_request": {
                    "fields": readback_request_fields,
                    "allowed_channels": list(READBACK_ALLOWED_CHANNELS),
                    "max_async_window_size": [int(MAX_ASYNC_READBACK_WIDTH), int(MAX_ASYNC_READBACK_HEIGHT)],
                    "field_types": {
                        "request_id": {"type": "int", "optional": True},
                        "center_x": {"type": "int", "optional": True},
                        "center_y": {"type": "int", "optional": True},
                        "width": {"type": "int"},
                        "height": {"type": "int"},
                        "channels": {"type": "str[]"},
                        "observer_id": {"type": "int", "optional": True},
                        "label": {"type": "str", "optional": True},
                        "target_query_id": {"type": "str", "optional": True},
                        "target_dx": {"type": "int"},
                        "target_dy": {"type": "int"},
                    },
                },
                "world_command": {
                    "fields": ["kind", "payload"],
                    "public_kinds": public_world_command_kinds,
                    "target_query_overlay_fields": ["target_query_id", "target_dx", "target_dy"],
                    "material_alias_fields_by_kind": world_command_material_alias_fields_by_kind,
                    "collection_item_types_by_kind": world_command_collection_item_types_by_kind,
                    "field_types": {
                        "kind": {"type": "str"},
                        "payload": {"type": "json"},
                    },
                },
            },
        },
        "frame_preview": {
            "field_order": frame_preview_field_order,
            "fields": {
                "controller_state": {"type": "json"},
                "resolved_targets": {"type": "resolved_target{}", "key": "query_id"},
                "resolved_change_intents": {"type": "resolved_change_intent{}", "key": "intent_id"},
                "resolved_carrier_intents": {"type": "resolved_carrier_intent{}", "key": "intent_id"},
                "resolved_commands": {"type": "world_command[]"},
                "observation_requests": {"type": "readback_request[]"},
                "observation_plans": {"type": "observation_plan[]"},
                "readback_requests": {"type": "readback_request[]"},
                "readback_plans": {"type": "readback_plan[]"},
                "bridge_frame_snapshot": {"type": "bridge_frame_snapshot"},
                "paging_updates": {"type": "page_stripe_update[]"},
                "placeholder_count": {"type": "int"},
            },
        },
        "frame_output": {
            "field_order": frame_output_field_order,
            "fields": {
                "frame_id": {"type": "int"},
                "submission_id": {"type": "int", "optional": True},
                "controller_state": {"type": "json"},
                "consumed_readbacks": {"type": "readback_result[]"},
                "resolved_targets": {"type": "resolved_target{}", "key": "query_id"},
                "resolved_change_intents": {"type": "resolved_change_intent{}", "key": "intent_id"},
                "resolved_carrier_intents": {"type": "resolved_carrier_intent{}", "key": "intent_id"},
                "observations": {"type": "observation_result{}", "key": "observer_id"},
                "entity_feedback": {"type": "entity_feedback{}", "key": "entity_id"},
                "paging_updates": {"type": "page_stripe_update[]"},
                "observation_plans": {"type": "observation_plan[]"},
                "readback_plans": {"type": "readback_plan[]"},
                "bridge_upload_snapshot": {"type": "bridge_upload_snapshot"},
                "bridge_frame_snapshot": {"type": "bridge_frame_snapshot"},
                "queued_observations": {"type": "int"},
                "queued_readbacks": {"type": "int"},
                "queued_commands": {"type": "int"},
                "placeholder_count": {"type": "int"},
            },
        },
        "frame_output_poll": {
            "fields": ["ready", "status", "output"],
            "field_types": {
                "ready": {"type": "bool"},
                "status": {"type": "str"},
                "output": {"type": "frame_output", "optional": True},
            },
        },
        "frame_output_ready": {
            "fields": ["ready", "outputs"],
            "field_types": {
                "ready": {"type": "int"},
                "outputs": {"type": "frame_output[]"},
            },
        },
        "frame_output_poll_all": {
            "fields": ["outputs"],
            "field_types": {
                "outputs": {"type": "frame_output[]"},
            },
        },
        "frame_cycle_result": {
            "fields": ["ok", "applied", "queued", "pending_frames", "submission_id", "preview", "result"],
            "preview_type": "frame_preview",
            "result_type": "frame_output",
            "result_optional_when_unapplied": True,
            "result_optional_when_deferred": True,
            "submission_id_optional_when_unapplied": True,
            "queueing": "deferred_frame_when_applied",
        },
        "frame_submit_result": {
            "fields": ["ok", "queued", "pending_frames", "submission_id", "preview"],
            "preview_type": "frame_preview",
            "submission_id_optional": False,
            "queueing": "deferred_frame",
        },
    }
