#version 430
layout(local_size_x=1, local_size_y=1, local_size_z=1) in;
layout(std430, binding=0) buffer ActiveMetaBuffer {
    int active_meta[];
};
layout(std430, binding=1) buffer ActiveChunkCountBuffer {
    uint active_chunk_count[];
};
layout(std430, binding=2) buffer ActiveChunkDispatchArgsBuffer {
    uint active_chunk_dispatch_args[];
};
void main() {
    active_meta[7] = 0;
    active_meta[8] = 0;
    active_chunk_count[0] = 0u;
    active_chunk_dispatch_args[0] = 0u;
    active_chunk_dispatch_args[1] = 1u;
    active_chunk_dispatch_args[2] = 1u;
}
