from __future__ import annotations

from typing import Callable

from oracle_game.types import Phase


# Each sub-builder receives the shared add closure (defined in rules.py's
# _build_materials) which assigns material_id = len(defs) + 1.  The sub-builders
# are invoked in the exact order below so material IDs stay identical.


def _build_terrain_materials(add: Callable[..., None]) -> None:
    add(
        "sand_powder",
        "沙子",
        Phase.POWDER,
        (0.82, 0.72, 0.45),
        render_group="powder",
        density=1.55,
        gravity_scale=1.0,
        wind_coupling=0.12,
        drag_scale=0.22,
        friction=0.55,
        elasticity=0.05,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=40,
        heat_capacity=0.65,
        conductivity=0.18,
        ambient_exchange_rate=0.08,
        melt_point=1250,
        melt_to_material="sandstone_solid",
        tags=("soil", "granular", "chaos_convert"),
    )
    add(
        "gravel_powder",
        "沙砾",
        Phase.POWDER,
        (0.55, 0.53, 0.50),
        render_group="powder",
        density=1.95,
        gravity_scale=1.05,
        wind_coupling=0.08,
        drag_scale=0.18,
        friction=0.6,
        elasticity=0.07,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=60,
        heat_capacity=0.75,
        conductivity=0.25,
        ambient_exchange_rate=0.05,
        tags=("stone", "granular"),
    )
    add(
        "soil_powder",
        "土壤",
        Phase.POWDER,
        (0.39, 0.27, 0.15),
        render_group="powder",
        density=1.25,
        gravity_scale=0.95,
        wind_coupling=0.14,
        drag_scale=0.24,
        friction=0.52,
        elasticity=0.04,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=35,
        heat_capacity=0.8,
        conductivity=0.15,
        ambient_exchange_rate=0.08,
        tags=("soil", "granular", "soft", "chaos_convert"),
    )


def _build_stone_materials(add: Callable[..., None]) -> None:
    add(
        "sandstone_solid",
        "砂岩",
        Phase.STATIC_SOLID,
        (0.71, 0.62, 0.36),
        render_group="stone",
        density=2.1,
        gravity_scale=0.0,
        wind_coupling=0.0,
        drag_scale=0.0,
        friction=0.85,
        elasticity=0.05,
        max_dda_step=0,
        structural=True,
        support_anchor=True,
        collapse_generation="sandstone_solid",
        powder_generation="sand_powder",
        base_integrity=140,
        heat_capacity=0.9,
        conductivity=0.35,
        ambient_exchange_rate=0.04,
        melt_point=1450,
        tags=("stone", "structural", "soft"),
    )
    add(
        "raw_stone_solid",
        "原石",
        Phase.STATIC_SOLID,
        (0.42, 0.45, 0.48),
        render_group="stone",
        density=2.5,
        gravity_scale=0.0,
        wind_coupling=0.0,
        drag_scale=0.0,
        friction=0.88,
        elasticity=0.03,
        max_dda_step=0,
        structural=True,
        support_anchor=True,
        collapse_generation="raw_stone_solid",
        powder_generation="gravel_powder",
        base_integrity=180,
        heat_capacity=1.0,
        conductivity=0.45,
        ambient_exchange_rate=0.03,
        melt_point=1600,
        tags=("stone", "structural"),
    )
    add(
        "obsidian_solid",
        "黑曜石",
        Phase.STATIC_SOLID,
        (0.10, 0.08, 0.14),
        render_group="stone",
        density=2.8,
        gravity_scale=0.0,
        wind_coupling=0.0,
        drag_scale=0.0,
        friction=0.9,
        elasticity=0.02,
        max_dda_step=0,
        structural=True,
        support_anchor=True,
        collapse_generation="obsidian_solid",
        powder_generation="gravel_powder",
        base_integrity=320,
        heat_capacity=1.2,
        conductivity=0.22,
        ambient_exchange_rate=0.02,
        melt_point=2200,
        tags=("stone", "structural", "acid_immune"),
    )


def _build_plant_materials(add: Callable[..., None]) -> None:
    add(
        "root_solid",
        "树根",
        Phase.STATIC_SOLID,
        (0.44, 0.30, 0.15),
        render_group="plant",
        density=1.05,
        gravity_scale=0.0,
        wind_coupling=0.04,
        drag_scale=0.01,
        friction=0.8,
        elasticity=0.03,
        max_dda_step=0,
        structural=True,
        support_anchor=False,
        collapse_generation="root_solid",
        powder_generation="soil_powder",
        base_integrity=90,
        heat_capacity=0.7,
        conductivity=0.10,
        ambient_exchange_rate=0.12,
        melt_point=260,
        tags=("plant", "flammable", "soft", "chaos_convert"),
    )
    add(
        "log_solid",
        "原木",
        Phase.STATIC_SOLID,
        (0.58, 0.37, 0.17),
        render_group="plant",
        density=0.95,
        gravity_scale=0.0,
        wind_coupling=0.03,
        drag_scale=0.01,
        friction=0.75,
        elasticity=0.04,
        max_dda_step=0,
        structural=True,
        support_anchor=False,
        collapse_generation="log_solid",
        powder_generation="soil_powder",
        base_integrity=110,
        heat_capacity=0.75,
        conductivity=0.11,
        ambient_exchange_rate=0.12,
        melt_point=280,
        tags=("plant", "flammable", "soft", "chaos_convert"),
    )
    add(
        "leaf_powder",
        "树叶",
        Phase.POWDER,
        (0.32, 0.68, 0.24),
        render_group="plant",
        density=0.35,
        gravity_scale=0.7,
        wind_coupling=0.4,
        drag_scale=0.35,
        friction=0.25,
        elasticity=0.08,
        max_dda_step=3,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=22,
        heat_capacity=0.35,
        conductivity=0.08,
        ambient_exchange_rate=0.18,
        tags=("plant", "flammable", "soft"),
    )
    add(
        "vine_solid",
        "藤蔓",
        Phase.STATIC_SOLID,
        (0.20, 0.52, 0.17),
        render_group="plant",
        density=0.65,
        gravity_scale=0.0,
        wind_coupling=0.05,
        drag_scale=0.02,
        friction=0.65,
        elasticity=0.05,
        max_dda_step=0,
        structural=True,
        support_anchor=False,
        collapse_generation="vine_solid",
        powder_generation="leaf_powder",
        base_integrity=55,
        heat_capacity=0.55,
        conductivity=0.09,
        ambient_exchange_rate=0.15,
        melt_point=220,
        tags=("plant", "flammable", "soft"),
    )
    add(
        "moss_powder",
        "苔藓",
        Phase.POWDER,
        (0.34, 0.58, 0.16),
        render_group="plant",
        density=0.45,
        gravity_scale=0.65,
        wind_coupling=0.25,
        drag_scale=0.32,
        friction=0.3,
        elasticity=0.05,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=18,
        heat_capacity=0.42,
        conductivity=0.07,
        ambient_exchange_rate=0.2,
        tags=("plant", "flammable", "soft", "chaos_convert"),
    )


def _build_metal_materials(add: Callable[..., None]) -> None:
    add(
        "iron_solid",
        "铁",
        Phase.STATIC_SOLID,
        (0.60, 0.64, 0.70),
        render_group="metal",
        density=4.0,
        gravity_scale=0.0,
        wind_coupling=0.0,
        drag_scale=0.0,
        friction=0.92,
        elasticity=0.10,
        max_dda_step=0,
        structural=True,
        support_anchor=True,
        collapse_generation="iron_solid",
        powder_generation="iron_powder",
        base_integrity=380,
        heat_capacity=1.1,
        conductivity=0.78,
        ambient_exchange_rate=0.04,
        melt_point=1538,
        melt_to_material="iron_liquid",
        tags=("metal", "structural"),
    )
    add(
        "iron_powder",
        "铁屑",
        Phase.POWDER,
        (0.52, 0.56, 0.62),
        render_group="metal",
        density=3.6,
        gravity_scale=0.82,
        wind_coupling=0.03,
        drag_scale=0.12,
        friction=0.42,
        elasticity=0.02,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=180,
        heat_capacity=1.0,
        conductivity=0.70,
        ambient_exchange_rate=0.05,
        melt_point=1538,
        melt_to_material="iron_liquid",
        tags=("metal", "powder"),
    )
    add(
        "iron_liquid",
        "熔铁",
        Phase.LIQUID,
        (0.96, 0.56, 0.18),
        render_group="liquid",
        density=3.9,
        gravity_scale=0.85,
        wind_coupling=0.04,
        drag_scale=0.08,
        friction=0.10,
        elasticity=0.0,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=340,
        heat_capacity=1.0,
        conductivity=0.74,
        ambient_exchange_rate=0.06,
        melt_point=1538,
        freeze_to_material="iron_solid",
        liquid_solver_kind="tile_level",
        tags=("metal", "liquid", "hot"),
    )
    add(
        "gold_solid",
        "金",
        Phase.STATIC_SOLID,
        (0.92, 0.75, 0.18),
        render_group="metal",
        density=5.2,
        gravity_scale=0.0,
        wind_coupling=0.0,
        drag_scale=0.0,
        friction=0.90,
        elasticity=0.08,
        max_dda_step=0,
        structural=True,
        support_anchor=True,
        collapse_generation="gold_solid",
        powder_generation="gold_powder",
        base_integrity=260,
        heat_capacity=1.05,
        conductivity=0.82,
        ambient_exchange_rate=0.03,
        melt_point=1064,
        melt_to_material="gold_liquid",
        tags=("metal", "structural", "acid_immune"),
    )
    add(
        "gold_powder",
        "金粉",
        Phase.POWDER,
        (0.90, 0.71, 0.18),
        render_group="metal",
        density=4.8,
        gravity_scale=0.80,
        wind_coupling=0.02,
        drag_scale=0.10,
        friction=0.40,
        elasticity=0.02,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=140,
        heat_capacity=1.0,
        conductivity=0.76,
        ambient_exchange_rate=0.04,
        melt_point=1064,
        melt_to_material="gold_liquid",
        tags=("metal", "powder", "acid_immune"),
    )
    add(
        "gold_liquid",
        "熔金",
        Phase.LIQUID,
        (1.00, 0.74, 0.16),
        render_group="liquid",
        density=5.0,
        gravity_scale=0.85,
        wind_coupling=0.03,
        drag_scale=0.08,
        friction=0.09,
        elasticity=0.0,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=240,
        heat_capacity=0.98,
        conductivity=0.78,
        ambient_exchange_rate=0.05,
        melt_point=1064,
        freeze_to_material="gold_solid",
        liquid_solver_kind="tile_level",
        tags=("metal", "liquid", "hot", "acid_immune"),
    )


def _build_water_materials(add: Callable[..., None]) -> None:
    add(
        "water_liquid",
        "水",
        Phase.LIQUID,
        (0.18, 0.42, 0.82),
        render_group="liquid",
        density=1.0,
        gravity_scale=0.85,
        wind_coupling=0.24,
        drag_scale=0.10,
        friction=0.12,
        elasticity=0.0,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=100,
        heat_capacity=1.5,
        conductivity=0.42,
        ambient_exchange_rate=0.28,
        melt_point=0,
        boil_point=100,
        freeze_to_material="water_solid",
        boil_to_gas_species="water_gas",
        liquid_solver_kind="tile_level",
        tags=("liquid", "coolant"),
    )
    add(
        "water_solid",
        "冰",
        Phase.STATIC_SOLID,
        (0.76, 0.88, 0.96),
        render_group="liquid",
        density=0.92,
        gravity_scale=0.0,
        wind_coupling=0.0,
        drag_scale=0.0,
        friction=0.08,
        elasticity=0.02,
        max_dda_step=0,
        structural=True,
        support_anchor=False,
        collapse_generation="water_solid",
        powder_generation="water_powder",
        base_integrity=90,
        heat_capacity=1.3,
        conductivity=0.35,
        ambient_exchange_rate=0.22,
        melt_point=0,
        melt_to_material="water_liquid",
        tags=("structural", "cold"),
    )
    add(
        "water_powder",
        "雪",
        Phase.POWDER,
        (0.88, 0.93, 0.98),
        render_group="powder",
        density=0.35,
        gravity_scale=0.78,
        wind_coupling=0.18,
        drag_scale=0.28,
        friction=0.18,
        elasticity=0.02,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=52,
        heat_capacity=1.1,
        conductivity=0.18,
        ambient_exchange_rate=0.18,
        melt_point=0,
        melt_to_material="water_liquid",
        boil_point=100,
        boil_to_gas_species="water_gas",
        tags=("cold", "granular"),
    )


def _build_poison_materials(add: Callable[..., None]) -> None:
    add(
        "poison_liquid",
        "毒液",
        Phase.LIQUID,
        (0.42, 0.82, 0.10),
        render_group="liquid",
        density=1.08,
        gravity_scale=0.85,
        wind_coupling=0.16,
        drag_scale=0.10,
        friction=0.10,
        elasticity=0.0,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=100,
        heat_capacity=0.95,
        conductivity=0.18,
        ambient_exchange_rate=0.12,
        melt_point=-20,
        freeze_to_material="poison_solid",
        boil_point=115,
        boil_to_gas_species="poison_gas",
        liquid_solver_kind="tile_level",
        tags=("liquid", "poison"),
    )
    add(
        "poison_solid",
        "毒冰",
        Phase.STATIC_SOLID,
        (0.68, 0.92, 0.24),
        render_group="liquid",
        density=1.02,
        gravity_scale=0.0,
        wind_coupling=0.0,
        drag_scale=0.0,
        friction=0.06,
        elasticity=0.01,
        max_dda_step=0,
        structural=True,
        support_anchor=False,
        collapse_generation="poison_solid",
        powder_generation="poison_powder",
        base_integrity=84,
        heat_capacity=0.90,
        conductivity=0.16,
        ambient_exchange_rate=0.10,
        melt_point=-20,
        melt_to_material="poison_liquid",
        tags=("structural", "poison", "cold"),
    )
    add(
        "poison_powder",
        "毒霜",
        Phase.POWDER,
        (0.74, 0.95, 0.30),
        render_group="powder",
        density=0.42,
        gravity_scale=0.78,
        wind_coupling=0.20,
        drag_scale=0.26,
        friction=0.18,
        elasticity=0.02,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=56,
        heat_capacity=0.82,
        conductivity=0.14,
        ambient_exchange_rate=0.12,
        melt_point=-20,
        melt_to_material="poison_liquid",
        boil_point=115,
        boil_to_gas_species="poison_gas",
        tags=("poison", "cold", "granular"),
    )


def _build_acid_materials(add: Callable[..., None]) -> None:
    add(
        "acid_liquid",
        "酸液",
        Phase.LIQUID,
        (0.95, 0.86, 0.20),
        render_group="liquid",
        density=1.12,
        gravity_scale=0.85,
        wind_coupling=0.12,
        drag_scale=0.12,
        friction=0.09,
        elasticity=0.0,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=100,
        heat_capacity=0.82,
        conductivity=0.14,
        ambient_exchange_rate=0.10,
        melt_point=-40,
        freeze_to_material="acid_solid",
        boil_point=108,
        boil_to_gas_species=None,
        liquid_solver_kind="tile_level",
        tags=("liquid", "acid"),
    )
    add(
        "acid_solid",
        "酸冰",
        Phase.STATIC_SOLID,
        (0.98, 0.94, 0.42),
        render_group="liquid",
        density=1.05,
        gravity_scale=0.0,
        wind_coupling=0.0,
        drag_scale=0.0,
        friction=0.05,
        elasticity=0.01,
        max_dda_step=0,
        structural=True,
        support_anchor=False,
        collapse_generation="acid_solid",
        powder_generation="acid_powder",
        base_integrity=88,
        heat_capacity=0.78,
        conductivity=0.12,
        ambient_exchange_rate=0.08,
        melt_point=-40,
        melt_to_material="acid_liquid",
        tags=("structural", "acid", "cold"),
    )
    add(
        "acid_powder",
        "酸霜",
        Phase.POWDER,
        (0.98, 0.96, 0.56),
        render_group="powder",
        density=0.46,
        gravity_scale=0.80,
        wind_coupling=0.18,
        drag_scale=0.24,
        friction=0.16,
        elasticity=0.02,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=60,
        heat_capacity=0.74,
        conductivity=0.10,
        ambient_exchange_rate=0.08,
        melt_point=-40,
        melt_to_material="acid_liquid",
        boil_point=108,
        boil_to_gas_species=None,
        tags=("acid", "cold", "granular"),
    )


def _build_oil_materials(add: Callable[..., None]) -> None:
    add(
        "oil_liquid",
        "油",
        Phase.LIQUID,
        (0.30, 0.22, 0.06),
        render_group="liquid",
        density=0.78,
        gravity_scale=0.85,
        wind_coupling=0.20,
        drag_scale=0.12,
        friction=0.10,
        elasticity=0.0,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=100,
        heat_capacity=0.70,
        conductivity=0.08,
        ambient_exchange_rate=0.07,
        melt_point=-50,
        freeze_to_material="oil_solid",
        boil_point=90,
        boil_to_gas_species="oil_gas",
        liquid_solver_kind="tile_level",
        tags=("liquid", "flammable"),
    )
    add(
        "oil_solid",
        "凝油",
        Phase.STATIC_SOLID,
        (0.48, 0.38, 0.16),
        render_group="liquid",
        density=0.82,
        gravity_scale=0.0,
        wind_coupling=0.0,
        drag_scale=0.0,
        friction=0.04,
        elasticity=0.01,
        max_dda_step=0,
        structural=True,
        support_anchor=False,
        collapse_generation="oil_solid",
        powder_generation="oil_powder",
        base_integrity=72,
        heat_capacity=0.66,
        conductivity=0.06,
        ambient_exchange_rate=0.05,
        melt_point=-50,
        melt_to_material="oil_liquid",
        tags=("structural", "flammable", "cold"),
    )
    add(
        "oil_powder",
        "油晶",
        Phase.POWDER,
        (0.54, 0.42, 0.18),
        render_group="powder",
        density=0.38,
        gravity_scale=0.76,
        wind_coupling=0.18,
        drag_scale=0.22,
        friction=0.14,
        elasticity=0.02,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=48,
        heat_capacity=0.60,
        conductivity=0.06,
        ambient_exchange_rate=0.05,
        melt_point=-50,
        melt_to_material="oil_liquid",
        boil_point=90,
        boil_to_gas_species="oil_gas",
        tags=("flammable", "cold", "granular"),
    )


def _build_special_materials(add: Callable[..., None]) -> None:
    add(
        "explosive_solid",
        "炸药",
        Phase.STATIC_SOLID,
        (0.80, 0.18, 0.15),
        render_group="special",
        density=1.35,
        gravity_scale=0.0,
        wind_coupling=0.0,
        drag_scale=0.0,
        friction=0.72,
        elasticity=0.02,
        max_dda_step=0,
        structural=True,
        support_anchor=False,
        collapse_generation="explosive_solid",
        powder_generation="soil_powder",
        base_integrity=55,
        heat_capacity=0.45,
        conductivity=0.10,
        ambient_exchange_rate=0.10,
        melt_point=140,
        tags=("flammable", "special", "soft"),
    )
    add(
        "phosphor_visible_powder",
        "可见荧光粉",
        Phase.POWDER,
        (0.92, 0.90, 0.68),
        render_group="special",
        density=0.62,
        gravity_scale=0.75,
        wind_coupling=0.20,
        drag_scale=0.18,
        friction=0.22,
        elasticity=0.03,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=32,
        heat_capacity=0.30,
        conductivity=0.05,
        ambient_exchange_rate=0.20,
        tags=("phosphor", "powder"),
    )
    add(
        "phosphor_holy_powder",
        "圣荧光粉",
        Phase.POWDER,
        (0.95, 0.95, 0.78),
        render_group="special",
        density=0.62,
        gravity_scale=0.75,
        wind_coupling=0.20,
        drag_scale=0.18,
        friction=0.22,
        elasticity=0.03,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=32,
        heat_capacity=0.30,
        conductivity=0.05,
        ambient_exchange_rate=0.20,
        tags=("phosphor", "powder"),
    )
    add(
        "phosphor_chaos_powder",
        "混沌荧光粉",
        Phase.POWDER,
        (0.90, 0.52, 0.12),
        render_group="special",
        density=0.62,
        gravity_scale=0.75,
        wind_coupling=0.20,
        drag_scale=0.18,
        friction=0.22,
        elasticity=0.03,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=32,
        heat_capacity=0.30,
        conductivity=0.05,
        ambient_exchange_rate=0.20,
        tags=("phosphor", "powder"),
    )
    add(
        "phosphor_magic_powder",
        "魔法荧光粉",
        Phase.POWDER,
        (0.16, 0.92, 0.90),
        render_group="special",
        density=0.62,
        gravity_scale=0.75,
        wind_coupling=0.20,
        drag_scale=0.18,
        friction=0.22,
        elasticity=0.03,
        max_dda_step=2,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=32,
        heat_capacity=0.30,
        conductivity=0.05,
        ambient_exchange_rate=0.20,
        tags=("phosphor", "powder"),
    )
    add(
        "pollution_powder",
        "污染物",
        Phase.POWDER,
        (0.42, 0.14, 0.44),
        render_group="special",
        density=0.28,
        gravity_scale=0.0,
        wind_coupling=0.35,
        drag_scale=0.06,
        friction=0.01,
        elasticity=0.0,
        max_dda_step=3,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=48,
        heat_capacity=0.40,
        conductivity=0.03,
        ambient_exchange_rate=0.22,
        boil_point=80,
        boil_to_gas_species="pollution_gas",
        powder_solver_kind="suspended",
        tags=("pollution", "powder", "chaos_convert"),
    )
    add(
        "vortex_heart_solid",
        "漩涡之心",
        Phase.STATIC_SOLID,
        (0.20, 0.80, 0.90),
        render_group="special",
        density=1.8,
        gravity_scale=0.0,
        wind_coupling=0.0,
        drag_scale=0.0,
        friction=0.50,
        elasticity=0.2,
        max_dda_step=0,
        structural=True,
        support_anchor=False,
        collapse_generation="vortex_heart_solid",
        powder_generation="gravel_powder",
        base_integrity=160,
        heat_capacity=1.2,
        conductivity=0.5,
        ambient_exchange_rate=0.16,
        tags=("special",),
    )
    add(
        "fire_powder",
        "火焰",
        Phase.POWDER,
        (1.00, 0.38, 0.10),
        render_group="special",
        density=0.08,
        gravity_scale=-0.25,
        wind_coupling=0.5,
        drag_scale=0.25,
        friction=0.0,
        elasticity=0.0,
        max_dda_step=3,
        structural=False,
        support_anchor=False,
        collapse_generation=None,
        powder_generation=None,
        base_integrity=12,
        heat_capacity=0.12,
        conductivity=0.05,
        ambient_exchange_rate=0.4,
        spawn_temperature=180.0,
        tags=("fire", "hot"),
    )
    add(
        "placeholder_solid",
        "占位体",
        Phase.STATIC_SOLID,
        (0.75, 0.12, 0.55),
        render_group="placeholder",
        density=3.0,
        gravity_scale=0.0,
        wind_coupling=0.0,
        drag_scale=0.0,
        friction=0.92,
        elasticity=0.04,
        max_dda_step=0,
        structural=False,
        support_anchor=False,
        collapse_generation="placeholder_solid",
        powder_generation="soil_powder",
        base_integrity=240,
        heat_capacity=1.0,
        conductivity=0.2,
        ambient_exchange_rate=0.12,
        tags=("placeholder", "soft"),
    )


