#version 430
layout(local_size_x=1, local_size_y=1, local_size_z=1) in;

uniform uint edge_group_count;

layout(std430, binding=0) buffer UnionChanged {
    uint union_changed[];
};
layout(std430, binding=1) writeonly buffer UnionDispatchArgs {
    uint union_dispatch_args[];
};

void main() {
    union_dispatch_args[0] = union_changed[0] != 0u ? edge_group_count : 0u;
    union_dispatch_args[1] = 1u;
    union_dispatch_args[2] = 1u;
    union_changed[0] = 0u;
}
